### ISSUE TITLE
Initial Style Guide

### ISSUE THREAD

**Issue by davelahaye** [brentmclark/wednesday-night-magic#2]
### Build initial style guide.

- [x] Design logo
- [x] Choose primary font
- [x] Design color palette (Accessibility Friendly)
- [x] (optional) Dark Mode

**Comment by davelahaye** [comment]
@brentmclark,take a look and let me know if you have any concerns with the initial style guide.  Happy to make any updates or changes.
[Initial-Style-Guide.pdf](https://github.com/brentmclark/wednesday-night-magic/files/4397734/Initial-Style-Guide.pdf)

**Comment by brentmclark** [comment]
I think this looks fantastic.  I love the logo, the colors, the backgrounds; all of it!

Also, suuuuuuuper impressive use of colors that work with both light and dark backgrounds and fonts.  How damn.  That's going to be a huge time saving when it comes to maintaining light and dark mode.  👏 👏 👏
